blocked_cmds:
- home
- tp
- tpa
- spawn
- warp
- back
- tpahere
- tphere
- s
- gamemode
- gm
- v
- vanish
- togglekeepinven
- skull
- togglepvp
- togglekeepxp
- enderchest
- wb
- sethome
